/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as humanFiGovernanceSol from "./HumanFiGovernance.sol";
export type { humanFiGovernanceSol };
import type * as security from "./security";
export type { security };
export type { HumanFiTreasury } from "./HumanFiTreasury";
export type { MockERC20 } from "./MockERC20";
export type { MockWLD } from "./MockWLD";
